ARG type

FROM alpine AS base

RUN apk add iperf3


FROM base AS client

RUN  apk add netcat-openbsd iproute2 bash

ENV SERVER=iperf-server

COPY --from=registry.ultraxime.fr/dns /dns-client.sh /

COPY client.sh /client.sh

ENTRYPOINT /client.sh


FROM base AS server

EXPOSE 5201

ENTRYPOINT iperf3 -s


FROM ${type}
