version: "3.9"

services:
  proxy-server:
    image: maximebruno/proxy-server
    build:
      context: proxy
      args:
        type: server
    environment:
      SERVER: proxy-server:4433

  proxy-client:
    image: maximebruno/proxy-client
    build:
      context: proxy
      args:
        type: client
    environment:
      CLIENT: proxy-client:8989
      SERVER: proxy-server:4433

  dns:
    image: maximebruno/dns
    build: dns

  gateway:
    image: maximebruno/gateway
    build: gateway

  browsertime-custom:
    image: maximebruno/browsertime-custom
    build: browsertime-custom

  speedtest:
    image: maximebruno/speedtest
    build: speedtest

  bulk_download:
    image: maximebruno/bulk_download
    build: bulk_download

  results-compilation:
    image: maximebruno/results-compilation
    build:
      context: results-compilation
      args:
        type: partial

  full-compilation:
    image: maximebruno/full-compilation
    build:
      context: results-compilation
      args:
        type: full
