version: "3.9"

services:
  results-compilation:
    image: maximebruno/results-compilation
    env_file: network.env
    volumes:
      - type: bind
        source: results
        target: /results
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.client==True"
    networks: []

  full-compilation:
    image: maximebruno/full-compilation
    volumes:
      - type: bind
        source: results/results
        target: /results
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.client==True"
    networks: []

networks: {}
