FROM python:3.8-alpine AS building_stage

RUN apk add git g++ build-base lapack-dev gfortran

RUN git clone https://github.com/Ultraxime/errant.git

RUN python -m venv /opt/venv
# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .

RUN pip install -Ur requirements.txt


FROM python:3.8-alpine

RUN apk add bash iproute2 g++ lapack-dev

COPY --from=building_stage /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY --from=building_stage errant/errant errant/models.pickle errant/sample_from_distribution.py /
# COPY errant/errant errant/models.pickle errant/sample_from_distribution.py /

COPY entrypoint.sh /

ENTRYPOINT /entrypoint.sh