version: "3.9"

services:
  server:
    image: maximebruno/chromium-server
    build:
      context: .
      args:
        type: server
    restart: on-failure

  client:
    image: maximebruno/chromium-client
    build:
      context: .
      args:
        type: client
    environment:
      proxy_addr: server:1024
    restart: on-failure
