FROM python:3-alpine AS building_stage

RUN python -m venv /opt/venv
# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .

RUN pip install -Ur requirements.txt


FROM python:3-alpine

RUN apk add tcpdump bash firefox rsync netcat-openbsd

COPY --from=building_stage /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY pyspeedtest/pyspeedtest /pyspeedtest

COPY --from=registry.ultraxime.fr/dns /dns-client.sh /

COPY speedtest.py /

COPY entrypoint.sh /

ENTRYPOINT /entrypoint.sh
