ARG type

FROM rust:alpine AS base

RUN apk add --upgrade git cmake build-base

WORKDIR /usr/src/

RUN git clone https://github.com/jromwu/masquerade.git

WORKDIR masquerade
RUN cargo build --bins

FROM base AS client

ENV port=8989
ENV ip=127.0.0.1
EXPOSE ${port}

ENV remote_ip=127.0.0.1
ENV remote_port=4433

ENV client_type=http

ENV log_level=warn

CMD RUST_LOG=${log_level} ./target/debug/client ${remote_ip}:${remote_port} ${ip}:${port} ${client_type}


FROM base AS server

ENV port=4433
ENV ip=127.0.0.1
EXPOSE ${port}/udp

ENV log_level=warn

CMD RUST_LOG=${log_level} ./target/debug/server ${ip}:${port}


FROM ${type}
